#' Create R Package Structure
#'
#' Creates a complete R package structure with best practices
#'
#' @param path Character. Path where the package should be created
#' @param package_name Character. Name of the package
#' @param title Character. Package title (default: derived from package_name)
#' @param description Character. Package description
#' @param author_name Character. Author name
#' @param author_email Character. Author email
#' @param license Character. License type (default: "MIT")
#' @param create_logo Logical. Whether to create a logo template (default: TRUE)
#'
#' @return Invisibly returns the package path
#' @export
#' @examples
#' \dontrun{
#' create_package_structure(
#'   path = "mypackage",
#'   package_name = "mypackage",
#'   author_name = "Your Name",
#'   author_email = "your.email@example.com"
#' )
#' }
create_package_structure <- function(
    path,
    package_name = basename(path),
    title = gsub("([a-z])([A-Z])", "\\1 \\2", package_name),
    description = "What the package does (one line, title case)",
    author_name = "Your Name",
    author_email = "your.email@example.com",
    license = "MIT",
    create_logo = TRUE,
    git = TRUE,
    repo = NULL,
    languages = c("R"),
    renv = FALSE
) {

  # Create main directory
  if (!dir.exists(path)) {
    dir.create(path, recursive = TRUE)
  }

  littlegit(path, git = git, repo = repo)

  if (git) {
    littlegitignore(path, languages, renv)
  }
  message("Initialized renv for project.")

  # Create standard R package directories
  dirs <- c("R", "man", "tests/testthat", "data", "data-raw", "inst", "vignettes")
  for (d in dirs) {
    dir.create(file.path(path, d), recursive = TRUE, showWarnings = FALSE)
  }

  if (git) {
    littlegitignore(path, languages)
  }

  # Create DESCRIPTION file
  description_content <- c(
    paste0("Package: ", package_name),
    "Type: Package",
    paste0("Title: ", title),
    "Version: 0.1.0",
    paste0("Authors@R: person(\"", author_name, "\", \"", author_name,
           "\", email = \"", author_email, "\","),
    "                  role = c(\"aut\", \"cre\"))",
    paste0("Description: ", description),
    paste0("License: ", license),
    "Encoding: UTF-8",
    "LazyData: true",
    "Roxygen: list(markdown = TRUE)",
    "RoxygenNote: 7.2.3",
    "Suggests:",
    "    testthat (>= 3.0.0),",
    "    knitr,",
    "    rmarkdown",
    "Config/testthat/edition: 3",
    "VignetteBuilder: knitr"
  )

  writeLines(description_content, file.path(path, "DESCRIPTION"))

  # Create NAMESPACE file
  writeLines("# Generated by roxygen2: do not edit by hand",
             file.path(path, "NAMESPACE"))

  # Create README.md
  readme_content <- c(
    paste0("# ", package_name),
    "",
    paste0("## Overview"),
    "",
    description,
    "",
    "## Installation",
    "",
    "```r",
    "# Install from GitHub (when available)",
    paste0("# devtools::install_github(\"yourusername/", package_name, "\")"),
    "",
    "# Or install from local source",
    paste0("# devtools::install(\"path/to/", package_name, "\")"),
    "```",
    "",
    "## Usage",
    "",
    "```r",
    paste0("library(", package_name, ")"),
    "",
    "# Your examples here",
    "```",
    "",
    "## License",
    "",
    paste0(license, " License")
  )

  writeLines(readme_content, file.path(path, "README.md"))

  # Create .Rbuildignore
  rbuildignore_content <- c(
    "^.*\\.Rproj$",
    "^\\.Rproj\\.user$",
    "^\\.git$",
    "^\\.gitignore$",
    "^README\\.Rmd$",
    "^LICENSE\\.md$",
    "^data-raw$",
    "^docs$",
    "^pkgdown$"
  )

  writeLines(rbuildignore_content, file.path(path, ".Rbuildignore"))

  # Create .gitignore
  gitignore_content <- c(
    ".Rproj.user",
    ".Rhistory",
    ".RData",
    ".Ruserdata",
    "*.Rproj",
    "docs/",
    "inst/doc"
  )

  writeLines(gitignore_content, file.path(path, ".gitignore"))

  # Create testthat.R
  testthat_content <- c(
    paste0("library(testthat)"),
    paste0("library(", package_name, ")"),
    "",
    paste0("test_check(\"", package_name, "\")")
  )

  writeLines(testthat_content, file.path(path, "tests/testthat.R"))

  # Create example test file
  test_content <- c(
    paste0("test_that(\"", package_name, " works\", {"),
    "  expect_true(TRUE)",
    "})"
  )

  writeLines(test_content, file.path(path, "tests/testthat/test-example.R"))

  # Create example function
  example_function_content <- c(
    "#' Example Function",
    "#'",
    "#' This is an example function to demonstrate package structure.",
    "#'",
    "#' @param x A numeric value",
    "#'",
    "#' @return A numeric value",
    "#' @export",
    "#'",
    "#' @examples",
    "#' example_function(5)",
    "example_function <- function(x) {",
    "  return(x * 2)",
    "}"
  )

  writeLines(example_function_content, file.path(path, "R/example_function.R"))

  # Create package documentation file
  package_doc_content <- c(
    paste0("#' ", package_name),
    "#'",
    paste0("#' @description ", description),
    "#'",
    paste0("#' @name ", package_name, "-package"),
    paste0("#' @aliases ", package_name),
    "#' @docType package",
    paste0("#' @keywords package"),
    "NULL"
  )

  writeLines(package_doc_content, file.path(path, paste0("R/", package_name, "-package.R")))

  # Create logo if requested
  if (create_logo) {
    create_package_logo(path, package_name)
  }

  message("\nPackage structure created successfully at: ", normalizePath(path))
  message("\nNext steps:")
  message("1. Edit DESCRIPTION file with your package details")
  message("2. Add your functions to R/")
  message("3. Document functions with roxygen2 comments")
  message("4. Run devtools::document() to generate documentation")
  message("5. Run devtools::check() to check package")
  message("6. Customize the logo in man/figures/logo.svg if needed")

  invisible(normalizePath(path))
}
